version: "3.9"

services:
  devmachine01:
    build:
      context: ./devmachine01
    container_name: devmachine01
    volumes:
      - shared_git:/shared
    networks:
      - infranet
    tty: true
    user: devuser

  reposerver:
    build:
      context: ./reposerver
    container_name: reposerver
    volumes:
      - shared_git:/shared
    networks:
      - infranet
      - secnet
    tty: true
    user: root

  qabox:
    build:
      context: ./qabox
    container_name: qabox
    networks:
      - secnet
    tty: true

volumes:
  shared_git:

networks:
  infranet:
    driver: bridge
  secnet:
    driver: bridge
