FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install base tools
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    iputils-ping \
    net-tools \
    iproute2 \
    lsof \
    nano \
    vim \
    git \
    cron \
    openssh-server \
    python3 \
    python3-pip \
    sudo


# Create qauser and set password
RUN useradd -ms /bin/bash qauser && \
    echo 'qauser:infragon' | chpasswd && \
    mkdir -p /home/qauser/.ssh && \
    touch /home/qauser/.ssh/authorized_keys && \
    chown -R qauser:qauser /home/qauser/.ssh && \
    chmod 700 /home/qauser/.ssh && \
    chmod 600 /home/qauser/.ssh/authorized_keys

# Set up cron directory and dummy log file
RUN mkdir -p /logs && \
    touch /logs/qa_validation.log && \
    chmod 666 /logs/qa_validation.log

# SSH config
RUN mkdir -p /var/run/sshd
RUN echo 'PermitRootLogin no' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config

# Copy entrypoint script
COPY entrypoint.sh /opt/.boot/entrypoint.sh
RUN chmod +x /opt/.boot/entrypoint.sh

# Set working directory
WORKDIR /home/qauser

# Switch to qauser after setup
USER qauser

# Launch
ENTRYPOINT ["/opt/.boot/entrypoint.sh"]
